import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.178.0/build/three.module.js';
import {CHAPTERS,ENEMIES,NPCS,ITEMS} from './game/content.js';
const $=id=>document.getElementById(id),game=$('game');
const state={hp:100,maxHp:100,qi:100,maxQi:100,xp:0,level:1,silver:240,quest:0,objective:0,damage:28,inventory:{herb:2,iron:0,jade:0},skills:{cloudstep:true,mooncut:false,ironwill:false},keys:{},attacking:false,enemy:null};
let scene,camera,renderer,clock,player,worldGroup,enemyGroup,npcGroup,spawned=[];const moveDir=new THREE.Vector3();
const mat=(c,r=.8)=>new THREE.MeshStandardMaterial({color:c,roughness:r});
const box=(w,h,d,c)=>new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c));
const cyl=(r,h,c)=>new THREE.Mesh(new THREE.CylinderGeometry(r,r*.82,h,10),mat(c));
function tree(x,z,s=1){let g=new THREE.Group(),t=cyl(.24*s,1.5*s,0x493126);t.position.y=.75*s;g.add(t);for(let i=0;i<3;i++){let c=new THREE.Mesh(new THREE.ConeGeometry((1.3-i*.2)*s,2.1*s,8),mat(i===2?0x16382f:0x1d5140));c.position.y=(2+i*.95)*s;g.add(c)}g.position.set(x,0,z);worldGroup.add(g)}
function house(x,z,s=1){let g=new THREE.Group(),b=box(3.8*s,2.4*s,3*s,0x76553d);b.position.y=1.2*s;g.add(b);let r=new THREE.Mesh(new THREE.ConeGeometry(2.8*s,1.5*s,4),mat(0x33292a));r.rotation.y=Math.PI/4;r.position.y=3*s;g.add(r);g.position.set(x,0,z);worldGroup.add(g)}
function modelCharacter(color,scale=1){let g=new THREE.Group(),body=cyl(.5*scale,1.6*scale,color);body.position.y=.95*scale;g.add(body);let head=new THREE.Mesh(new THREE.SphereGeometry(.4*scale,12,8),mat(0xd0a27f));head.position.y=2*scale;g.add(head);let hair=cyl(.43*scale,.3*scale,0x171d1d);hair.position.y=2.3*scale;g.add(hair);g.traverse(o=>o.castShadow=true);return g}
function init(){scene=new THREE.Scene();scene.background=new THREE.Color(0x102f2d);scene.fog=new THREE.Fog(0x102f2d,35,125);camera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,220);renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;game.innerHTML='';game.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xb8dfd5,0x17251f,2));let sun=new THREE.DirectionalLight(0xd9e8df,2.8);sun.position.set(-30,45,20);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);scene.add(sun);worldGroup=new THREE.Group();enemyGroup=new THREE.Group();npcGroup=new THREE.Group();scene.add(worldGroup,enemyGroup,npcGroup);buildWorld();player=modelCharacter(0x294d49);player.position.set(0,0,20);let sword=box(.12,2.3,.16,0xd8d6c7);sword.position.set(.75,1.2,0);sword.rotation.z=-.35;player.add(sword);scene.add(player);spawnNPCs();spawnEnemies();clock=new THREE.Clock();updateHud();$('locationName').textContent='Moonreed Valley';setTimeout(()=>{$('loading').classList.add('gone');toast('Chapter I · Echoes Beneath the Reeds')},900);animate()}
function buildWorld(){let ground=box(110,.5,110,0x173c31);ground.position.y=-.3;ground.receiveShadow=true;worldGroup.add(ground);let river=box(9,.08,105,0x286d68);river.position.set(13,.02,0);river.rotation.y=-.12;worldGroup.add(river);let path=box(5,.1,100,0x746247);path.position.set(-2,.03,0);path.rotation.y=.18;worldGroup.add(path);for(let i=0;i<95;i++){let a=Math.random()*Math.PI*2,r=30+Math.random()*34;tree(Math.cos(a)*r,Math.sin(a)*r,.65+Math.random()*.65)}for(let i=0;i<8;i++)house(-22+i*4.5,-11+(i%2)*4,.75);let shrine=box(7,.3,7,0x5c4b39);shrine.position.set(27,.2,-28);worldGroup.add(shrine);for(let x of [24,30]){let p=box(.45,5,.45,0x8b4939);p.position.set(x,2.5,-28);worldGroup.add(p)}let beam=box(6.5,.45,.45,0x9a4d39);beam.position.set(27,5,-28);worldGroup.add(beam)}
function spawnNPCs(){for(const n of NPCS){let g=modelCharacter(n.id==='merchant'?0x7a6746:n.id==='ren'?0x5d3d65:0x8c6b42,.9);g.position.set(n.x,0,n.z);g.userData=n;npcGroup.add(g)}}
function spawnEnemies(){const spots=[['wraith',4,8],['bandit',-15,-24],['bandit',22,5],['fox',-29,20],['fox',32,25],['warden',27,-35]];for(const [id,x,z] of spots){let d=ENEMIES.find(e=>e.id===id),g=modelCharacter(d.color,d.scale);g.position.set(x,0,z);g.userData={...d,baseHp:d.hp};enemyGroup.add(g);spawned.push(g)}}
function updateHud(){$('hpBar').style.width=state.hp/state.maxHp*100+'%';$('qiBar').style.width=state.qi/state.maxQi*100+'%';$('xp').textContent=state.xp;$('level').textContent=state.level;$('questTitle').textContent=CHAPTERS[state.quest].title;$('questText').textContent=CHAPTERS[state.quest].objectives[state.objective]||CHAPTERS[state.quest].summary}
function nearestEnemy(){let best=null,bd=6;for(const e of spawned)if(e.visible){let d=player.position.distanceTo(e.position);if(d<bd){best=e;bd=d}}return best}
function attack(){if(state.attacking)return;let e=state.enemy||nearestEnemy();if(!e){toast('No enemy within striking distance');return}state.enemy=e;state.attacking=true;player.rotation.y+=.8;setTimeout(()=>{let dmg=state.damage+(state.skills.mooncut?10:0);e.userData.hp-=dmg;toast(`${e.userData.name} · -${dmg} HP`);if(e.userData.hp<=0){e.visible=false;state.xp+=e.userData.xp;state.silver+=Math.round(e.userData.xp/2);state.objective=Math.min(2,state.objective+1);if(state.xp>=100){state.level++;state.xp-=100;state.maxHp+=12;state.maxQi+=8;state.damage+=4;toast('Level up! New power flows through you.')}updateHud();}state.attacking=false},240)}
function dash(){if(state.qi<18){toast('Not enough Qi');return}state.qi-=18;moveDir.set(0,0,-1).applyQuaternion(player.quaternion);player.position.addScaledVector(moveDir,6);updateHud();toast('Cloudstep')}
function heal(){if(!state.inventory.herb){toast('No Moonleaf Herbs');return}state.inventory.herb--;state.hp=Math.min(state.maxHp,state.hp+25);updateHud();toast('Moonleaf restores 25 HP')}
function interact(){let e=nearestEnemy();if(e){dialogue(e.userData.name,'The creature watches you as if it recognises the jade mark on your hand.',['Attack','Back away']);return}let npc=npcGroup.children.reduce((a,n)=>{let d=player.position.distanceTo(n.position);return d<a.d?a:{n,d}},{n:null,d:7});if(npc.n){if(npc.n.userData.id==='merchant')shop();else dialogue(npc.n.userData.name,npc.n.userData.text,['Tell me more','Goodbye']);return}if(player.position.distanceTo(new THREE.Vector3(27,0,-28))<9){dialogue('Old Moon Shrine','The stone seal glows beneath your palm. A bell answers from underground.',['Open the moon seal','Leave it']);return}toast('Nothing nearby to interact with')}
function dialogue(s,t,choices){$('speaker').textContent=s;$('dialogueText').textContent=t;$('choices').innerHTML=choices.map(c=>`<button>${c}</button>`).join('');$('dialogue').classList.remove('hidden');document.querySelectorAll('#choices button').forEach((b,i)=>b.onclick=()=>{$('dialogue').classList.add('hidden');if(i===0&&s==='Mist Wraith')attack();else toast('Your choice has consequences')})}
function shop(){dialogue('Old Bo','Silver for steel, herbs for bruises. Choose carefully.',['Buy Iron Jian · 90 silver','Buy Moonleaf · 12 silver','Leave']);document.querySelectorAll('#choices button').forEach((b,i)=>b.onclick=()=>{if(i===0&&state.silver>=90){state.silver-=90;state.inventory.iron++;state.damage+=12;toast('Iron Jian equipped')}else if(i===1&&state.silver>=12){state.silver-=12;state.inventory.herb++;toast('Moonleaf added')}else if(i<2)toast('Not enough silver');$('dialogue').classList.add('hidden');updateHud()})}
function skills(){dialogue('Jade Meridian','Choose a technique to deepen your martial path.',['Mooncut · +10 damage','Iron Will · +30 max HP','Close']);document.querySelectorAll('#choices button').forEach((b,i)=>b.onclick=()=>{if(i===0&&!state.skills.mooncut){state.skills.mooncut=true;toast('Mooncut learned')}if(i===1&&!state.skills.ironwill){state.skills.ironwill=true;state.maxHp+=30;state.hp+=30;toast('Iron Will learned')}$('dialogue').classList.add('hidden');updateHud()})}
function move(dt){moveDir.set(0,0,0);if(state.keys.w||state.keys.ArrowUp)moveDir.z-=1;if(state.keys.s||state.keys.ArrowDown)moveDir.z+=1;if(state.keys.a||state.keys.ArrowLeft)moveDir.x-=1;if(state.keys.d||state.keys.ArrowRight)moveDir.x+=1;if(moveDir.lengthSq()){moveDir.normalize();player.position.addScaledVector(moveDir,dt*9);player.rotation.y=Math.atan2(moveDir.x,moveDir.z);state.qi=Math.min(state.maxQi,state.qi+dt*4)}player.position.x=Math.max(-48,Math.min(48,player.position.x));player.position.z=Math.max(-48,Math.min(48,player.position.z));camera.position.lerp(new THREE.Vector3(player.position.x,8,player.position.z+11),.08);camera.lookAt(player.position.x,1.3,player.position.z);updateHud()}
function animate(){requestAnimationFrame(animate);let dt=Math.min(clock.getDelta(),.05);move(dt);for(const e of spawned)if(e.visible){e.position.y=Math.sin(performance.now()*.002+e.position.x)*.08;if(e.userData.id==='fox')e.rotation.y+=dt*.7}renderer.render(scene,camera)}
let joy=false,lx=0,ly=0;$('attack').onclick=attack;$('dash').onclick=dash;$('interact').onclick=interact;$('menuBtn').onclick=()=>$('menu').classList.remove('hidden');$('closeMenu').onclick=()=>$('menu').classList.add('hidden');$('resume').onclick=()=>$('menu').classList.add('hidden');
$('joystick').addEventListener('pointerdown',e=>{joy=true;lx=e.clientX;ly=e.clientY;e.currentTarget.setPointerCapture(e.pointerId)});$('joystick').addEventListener('pointermove',e=>{if(!joy)return;let dx=e.clientX-lx,dy=e.clientY-ly;if(Math.abs(dx)+Math.abs(dy)>4){state.keys.a=dx<0;state.keys.d=dx>0;state.keys.w=dy<0;state.keys.s=dy>0;lx=e.clientX;ly=e.clientY}});['pointerup','pointercancel'].forEach(v=>$('joystick').addEventListener(v,()=>{joy=false;state.keys.a=state.keys.d=state.keys.w=state.keys.s=false}));
window.addEventListener('keydown',e=>{state.keys[e.key]=true;if(e.key===' ')attack();if(e.key.toLowerCase()==='e')interact();if(e.key.toLowerCase()==='shift')dash();if(e.key.toLowerCase()==='h')heal();if(e.key.toLowerCase()==='k')skills()});window.addEventListener('keyup',e=>state.keys[e.key]=false);window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
init();
